type: mpc
mpc:
  model_name: dingo
  n: 3
  time_horizon: 10
  time_step: 0.1
  slack: False
  interval: 1
  initialization: previous_plan
  constraints:
    - RadialConstraints
    - SelfCollisionAvoidanceConstraints
    - JointLimitConstraints
    - InputLimitConstraints
  weights:
    w: 1.0
    wvel: [0.0, 0.0, 0.0, 1, 0.01]
    ws: 1e10
    wu: 0.01
    wobst: 0.5
  number_obstacles: 1
  control_mode: "acc"
robot:
  collision_links: 
    - chasis_link
  selfCollision:
    pairs:  []
  urdf_file: dingo-o.urdf
  root_link: base_link
  end_link: chasis_link
  base_type: holonomic
