[tool.poetry]
name = "robotmpcs"
version = "0.1.0"
description = "MPC generation for robots using ForcesPro."
authors = ["Max Spahn <m.spahn@tudelft.nl>"]

[tool.poetry.dependencies]
python = "^3.7,<3.11"
numpy = "^1.15"
casadi = "<=3.5.5"
requests = "^2.27.1"
pyaml = "^21.10.1"
forwardkinematics = "^0.5"
planarenvs = {git = "ssh://git@github.com/maxspahn/gym_envs_planar.git", rev = "ft-clean-build", optional = true}

[tool.poetry.dev-dependencies]

[tool.poetry.extras]
agents = ["planarenvs"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
